---
- hosts: "{{ hosts }}"
  vars:
    username: steam
    steamcmd_url: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
  tasks:
    - apt: name=lib32gcc1 state=present update_cache=yes
      become: yes

    - user: name="{{ username }}"
      become: yes

    - unarchive: src="{{ steamcmd_url }}" dest=~/steamcmd/
      become_user: "{{ username }}"

    - command: "./steamcmd +login <username> <password> +force_install_dir ../arma3 +app_update 233780 +validate +quit" chdir=~/steamcmd/
      become_user: "{{ username }}"
